version: '3.9'

services:
    app:
        build: .
        container_name: Lavest-app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - app_network

    db:
        image: mysql:8.0
        container_name: Lavest-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    db_data:
